### ISSUE TITLE
Ability to remove profile picture

### ISSUE THREAD

**Issue by iomintz** [pronouns/main#27]
Please allow us the ability to unset our profile picture.

**Comment by falkirks** [comment]
Profile pictures don't work right now at all because the service is hosted on Heroku, so doesn't have long term file storage. The pictures will end up disappearing eventually on their own. They also don't show up in profile pages. 

I really should be hiding the profile picture settings page, but that is another issue.

**Comment by iomintz** [comment]
If you want I can offer you a VM where you can host it. It may not have the same uptime as paid Heroku, but it works pretty well otherwise.

**Comment by falkirks** [comment]
@iomintz I really appreciate the offer. Heroku is useful for this because it requires very little maintenance on my part, which is why I have stuck with it over a VM.
