### ISSUE TITLE
Can't create a account

### ISSUE THREAD

**Issue by serogrem** [pronouns/main#36]
It simply keeps telling me something went wrong when I try to make a account via email.

**Comment by chumpyeet** [comment]
ive been having the same problem too, i dont know whats wrong

**Comment by mercymoo** [comment]
i’m having the issue too. wish i knew how to help, sorry :(

**Comment by possumkid** [comment]
im having this problem as well, i really wish i knew how to help, sry :(

**Comment by frogg1efriend** [comment]
i'm having this problem too D:

**Comment by falkirks** [comment]
I've looked into this and I can't seem to find a logical explanation. The service is under high load right now which could be causing database issues. I will need to investigate further.

**Comment by nikai1128** [comment]
i'm having this same problem, too... 😔

**Comment by gecprincess** [comment]
same omg i’m so sad

**Comment by electrikatty** [comment]
same

**Comment by falkirks** [comment]
This is now fixed. This was due to the database being over capacity, which shouldn't be an issue in a few days because I will be migrating the database onto a new server. However, to fix it for the time being I cleared out all the "alerts" records (which means all alerts will disappear and old links will break.

**Comment by falkirks** [comment]
I forgot to update here, but the migration happened so capacity issues should hopefully no longer be a thing.
