### ISSUE TITLE
Still cannot add new names

### ISSUE THREAD

**Issue by ODeorain** [pronouns/main#41]
Disregard if you're already working on this issue, but I want to be sure you know about this.  It seems to be a universal issue that we can't add names as of at least October 1st, as stated in another thread.  Is this something you are aware of?  Thanks!

**Comment by falkirks** [comment]
I'm sorry about this. I have been working on it since it was reported. It is not a universal issue because for the vast majority of users names continue to work correctly. I have made several test accounts and still have been unable to get it to break. But once I figure it out I will defintely push a fix.
